// utils/wpThemeBuilder/generators/newPageCss.js

const fs = require('fs');
const path = require('path');

/**
 * Generate new-page-layout.css by copying from an existing service page CSS
 * 
 * @param {string} distDir - Path to dist directory
 * @returns {string|null} - Path to generated CSS file or null if failed
 */
function generateNewPageLayoutCss(distDir) {
  const cssDir = path.join(distDir, 'css');
  
  // List of possible source CSS files (in priority order)
  const sourceCssFiles = [
    'water-heater-repair.css',
    'faucet-installation.css',
    'drain-cleaning.css',
    'emergency-plumbing.css',
  ];
  
  // Try to find an existing service page CSS file
  let sourceCssPath = null;
  for (const filename of sourceCssFiles) {
    const testPath = path.join(cssDir, filename);
    if (fs.existsSync(testPath)) {
      sourceCssPath = testPath;
      console.log(`   Using ${filename} as template for new-page-layout.css`);
      break;
    }
  }
  
  // If no source CSS found, return null
  if (!sourceCssPath) {
    console.warn('   ⚠️  No service page CSS found to use as template for new-page-layout.css');
    return null;
  }
  
  // Read the source CSS file
  const cssContent = fs.readFileSync(sourceCssPath, 'utf8');
  
  // Destination path
  const destCssPath = path.join(cssDir, 'new-page-layout.css');
  
  // Add a comment at the top explaining what this file is
  const header = `/**
 * New Page Layout CSS
 * 
 * This file is automatically generated from ${path.basename(sourceCssPath)}
 * All pages using the "New Page Layout" template will use this CSS.
 * 
 * To customize:
 * 1. Edit this file directly in dist/css/new-page-layout.css
 * 2. Regenerate the theme
 * 3. Upload to WordPress
 * 
 * Auto-generated: ${new Date().toISOString()}
 */

`;
  
  const finalContent = header + cssContent;
  
  // Write the new CSS file
  fs.writeFileSync(destCssPath, finalContent, 'utf8');
  
  console.log(`   ✅ Generated new-page-layout.css`);
  
  return destCssPath;
}

module.exports = {
  generateNewPageLayoutCss,
};