// utils/wpThemeBuilder/dataFiles/globalSettings.js

const { phpEscapeSingle } = require('../wpHelpers/phpHelpers');

/**
 * Generate the theme-global-settings.php data file
 * Contains site-wide settings like business info, contact details, social links
 *
 * @param {object} settings - Global settings object
 * @param {string} settings.business_name - Business name
 * @param {string} settings.business_type - Type of business (e.g., "Plumbing Company")
 * @param {string} settings.location - City, State
 * @param {string} settings.phone - Phone number
 * @param {string} settings.email - Email address
 * @param {string} settings.address - Full address
 * @param {string} settings.social_facebook - Facebook URL
 * @param {string} settings.social_twitter - Twitter URL
 * @param {string} settings.social_instagram - Instagram URL
 * @param {string} settings.social_linkedin - LinkedIn URL
 * @param {string} settings.social_youtube - YouTube URL
 * @param {string} settings.social_pinterest - Pinterest URL
 * @param {string} settings.google_map_cid - Google Maps CID
 * @returns {string} - Complete PHP array as string
 */
function generateGlobalSettingsPhp(settings) {
  if (!settings || typeof settings !== 'object') {
    return `<?php
/**
 * Theme Global Settings
 * This file is empty because no global settings were provided.
 */
return [];
`;
  }

  // Define all possible global settings with defaults
  const settingsFields = {
    // Business info
    business_name: settings.business_name || settings.businessName || '',
    business_type: settings.business_type || settings.businessType || '',
    location: settings.location || '',

    // Contact info
    phone: settings.phone || '',
    email: settings.email || '',
    address: settings.address || '',

    // Social media
    social_facebook: settings.social_facebook || settings.facebookUrl || '',
    social_twitter: settings.social_twitter || settings.twitterUrl || '',
    social_instagram: settings.social_instagram || settings.instagramUrl || '',
    social_linkedin: settings.social_linkedin || settings.linkedinUrl || '',
    social_youtube: settings.social_youtube || settings.youtubeUrl || '',
    social_pinterest: settings.social_pinterest || settings.pinterestUrl || '',

    // Additional settings
    google_map_cid: settings.google_map_cid || settings.googleMapCid || '',
  };

  // Filter out empty values
  const filteredSettings = {};
  Object.entries(settingsFields).forEach(([key, value]) => {
    if (value && String(value).trim() !== '') {
      filteredSettings[key] = String(value).trim();
    }
  });

  // Build PHP array entries
  const entries = Object.entries(filteredSettings).map(([key, value]) => {
    const escapedKey = phpEscapeSingle(key);
    const escapedValue = phpEscapeSingle(value);
    return `    '${escapedKey}' => '${escapedValue}'`;
  }).join(",\n");

  if (entries.length === 0) {
    return `<?php
/**
 * Theme Global Settings
 * No settings were provided or all settings were empty.
 */
return [];
`;
  }

  return `<?php
/**
 * Theme Global Settings
 * 
 * This file contains site-wide settings that apply across the entire website.
 * 
 * Settings include:
 * - Business information (name, type, location)
 * - Contact details (phone, email, address)
 * - Social media links
 * - Additional settings (Google Maps, etc.)
 * 
 * On theme activation, these settings are stored in wp_options and can be
 * edited through Appearance → Theme Settings in the WordPress admin.
 * 
 * This file is automatically generated from your static HTML build.
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return [
${entries}
];
`;
}

/**
 * Extract global settings from extracted HTML content
 * Pulls global info from the contentExtractor results
 *
 * @param {object} extractedContent - Content from contentExtractor.extractPageContent()
 * @returns {object} - Global settings object
 */
function extractGlobalFromContent(extractedContent) {
  if (!extractedContent || !extractedContent.global) {
    return {};
  }

  const global = extractedContent.global;
  const settings = {};

  // Map extracted fields to settings format
  if (global.phone) settings.phone = global.phone;
  if (global.email) settings.email = global.email;
  if (global.address) settings.address = global.address;

  // Social links
  if (global.social) {
    Object.entries(global.social).forEach(([platform, url]) => {
      settings[`social_${platform}`] = url;
    });
  }

  return settings;
}

/**
 * Merge global settings from multiple sources
 * Priority: later sources override earlier ones
 *
 * @param  {...object} settingsSources - Multiple settings objects to merge
 * @returns {object} - Merged settings object
 */
function mergeGlobalSettings(...settingsSources) {
  const merged = {};

  settingsSources.forEach(source => {
    if (source && typeof source === 'object') {
      Object.assign(merged, source);
    }
  });

  return merged;
}

/**
 * Normalize social media URLs
 * Ensures URLs are properly formatted
 *
 * @param {object} settings - Settings object with social URLs
 * @returns {object} - Settings with normalized URLs
 */
function normalizeSocialUrls(settings) {
  const normalized = { ...settings };

  const socialPlatforms = ['facebook', 'twitter', 'instagram', 'linkedin', 'youtube', 'pinterest'];

  socialPlatforms.forEach(platform => {
    const key = `social_${platform}`;
    if (normalized[key]) {
      let url = String(normalized[key]).trim();

      // Ensure URL starts with http:// or https://
      if (url && !url.startsWith('http://') && !url.startsWith('https://')) {
        url = 'https://' + url;
      }

      normalized[key] = url;
    }
  });

  return normalized;
}

/**
 * Validate global settings
 * Checks if required fields are present
 *
 * @param {object} settings - Settings object
 * @returns {object} - { valid: boolean, missing: array }
 */
function validateGlobalSettings(settings) {
  const requiredFields = ['business_name', 'phone']; // Minimum requirements
  const missing = [];

  requiredFields.forEach(field => {
    if (!settings[field] || String(settings[field]).trim() === '') {
      missing.push(field);
    }
  });

  return {
    valid: missing.length === 0,
    missing,
  };
}

/**
 * Get settings summary for logging
 * Shows which fields are populated
 *
 * @param {object} settings - Settings object
 * @returns {object} - Summary with boolean flags
 */
function getSettingsSummary(settings) {
  const summary = {
    hasBusinessName: !!settings.business_name,
    hasBusinessType: !!settings.business_type,
    hasLocation: !!settings.location,
    hasPhone: !!settings.phone,
    hasEmail: !!settings.email,
    hasAddress: !!settings.address,
    socialCount: 0,
    totalFields: 0,
  };

  // Count social platforms
  const socialPlatforms = ['facebook', 'twitter', 'instagram', 'linkedin', 'youtube', 'pinterest'];
  socialPlatforms.forEach(platform => {
    if (settings[`social_${platform}`]) {
      summary.socialCount++;
    }
  });

  // Count total populated fields
  summary.totalFields = Object.keys(settings).filter(key => {
    return settings[key] && String(settings[key]).trim() !== '';
  }).length;

  return summary;
}

/**
 * Format phone number for display
 * Converts various formats to a standard format
 *
 * @param {string} phone - Phone number in any format
 * @returns {string} - Formatted phone number (e.g., "(512) 555-1234")
 */
function formatPhoneNumber(phone) {
  if (!phone) return '';

  // Remove all non-digit characters
  const digits = phone.replace(/\D/g, '');

  // Format as (XXX) XXX-XXXX if 10 digits
  if (digits.length === 10) {
    return `(${digits.substr(0, 3)}) ${digits.substr(3, 3)}-${digits.substr(6, 4)}`;
  }

  // Return as-is if not 10 digits
  return phone;
}

module.exports = {
  generateGlobalSettingsPhp,
  extractGlobalFromContent,
  mergeGlobalSettings,
  normalizeSocialUrls,
  validateGlobalSettings,
  getSettingsSummary,
  formatPhoneNumber
};