// utils/wpThemeBuilder/dataFiles/themePages.js

const { phpEscapeSingle } = require('../wpHelpers/phpHelpers');

/**
 * Generate the theme-pages.php data file
 * Contains metadata for all pages to be created on theme activation
 *
 * @param {array} pages - Array of page objects
 * @param {string} pages[].title - Page title (e.g., "About Us")
 * @param {string} pages[].slug - Page slug (e.g., "about")
 * @param {string} pages[].template - Template filename (e.g., "front-page.php")
 * @param {number} pages[].menu_order - Order in menu (0, 1, 2, etc.)
 * @returns {string} - Complete PHP array as string
 */
function generateThemePagesPhp(pages) {
  if (!pages || !Array.isArray(pages) || pages.length === 0) {
    return `<?php
/**
 * Theme Pages Definition
 * This file is empty because no pages were provided.
 */
return [];
`;
  }

  // Build each page entry
  const entries = pages.map(page => {
    const title = phpEscapeSingle(page.title || '');
    const slug = phpEscapeSingle(page.slug || '');
    const template = phpEscapeSingle(page.template || '');
    const menuOrder = parseInt(page.menu_order || 0, 10);

    return `    [
        'title'      => '${title}',
        'slug'       => '${slug}',
        'template'   => '${template}',
        'menu_order' => ${menuOrder},
    ]`;
  }).join(",\n\n");

  return `<?php
/**
 * Theme Pages Definition
 * 
 * This file contains metadata for all pages to be created on theme activation.
 * 
 * Each page includes:
 * - title: The page title displayed in WordPress
 * - slug: The URL-friendly identifier
 * - template: The PHP template file to use (e.g., front-page.php)
 * - menu_order: The order in which pages appear in the navigation menu
 * 
 * This file is automatically generated from your static HTML build.
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return [
${entries}
];
`;
}

/**
 * Helper: Build page metadata array from HTML files
 * Converts file information into page definition objects
 *
 * @param {array} htmlFiles - Array of file info objects
 * @param {string} htmlFiles[].filename - Base filename without extension
 * @param {string} htmlFiles[].title - Page title
 * @param {string} htmlFiles[].slug - URL slug
 * @param {boolean} htmlFiles[].isFrontPage - Whether this is the front page
 * @param {number} htmlFiles[].menuOrder - Menu position
 * @returns {array} - Array of page definition objects
 */
function buildPageDefinitions(htmlFiles) {
  const pages = [];

  htmlFiles.forEach((file, index) => {
    const pageData = {
      title: file.title || file.filename,
      slug: file.slug || file.filename,
      menu_order: file.menuOrder !== undefined ? file.menuOrder : index,
    };

    // Determine template
    if (file.isFrontPage) {
      pageData.template = 'front-page.php';
    } else if (file.slug === 'about' || file.slug === 'home') {
      pageData.template = 'front-page.php';
    } else if (file.slug && file.slug.startsWith('location-')) {
      // Location pages use generic page template
      pageData.template = ''; // Uses default page.php
    } else if (file.slug) {
      // Service pages and others get slug-specific templates
      pageData.template = `page-${file.slug}.php`;
    } else {
      pageData.template = ''; // Uses default page.php
    }

    pages.push(pageData);
  });

  return pages;
}

/**
 * Add legal pages to page definitions
 * Privacy Policy, Terms of Use, Accessibility
 *
 * @param {array} existingPages - Existing page definitions
 * @returns {array} - Updated array with legal pages added
 */
function addLegalPages(existingPages) {
  const legalPages = [
    {
      title: 'Privacy Policy',
      slug: 'privacy-policy',
      template: 'page-privacy-policy.php',
      menu_order: 9998,
    },
    {
      title: 'Terms of Use',
      slug: 'terms-of-use',
      template: 'page-terms-of-use.php',
      menu_order: 9999,
    },
    {
      title: 'Accessibility',
      slug: 'accessibility',
      template: 'page-accessibility.php',
      menu_order: 10000,
    },
  ];

  return [...existingPages, ...legalPages];
}

/**
 * Sort pages by menu order
 *
 * @param {array} pages - Array of page definitions
 * @returns {array} - Sorted array
 */
function sortPagesByMenuOrder(pages) {
  return pages.sort((a, b) => {
    const orderA = a.menu_order || 0;
    const orderB = b.menu_order || 0;
    return orderA - orderB;
  });
}

module.exports = {
  generateThemePagesPhp,
  buildPageDefinitions,
  addLegalPages,
  sortPagesByMenuOrder
};