// utils/wpThemeBuilder/dataFiles/themeContent.js

const { nestedObjectToPhpArray, phpEscapeSingle } = require('../wpHelpers/phpHelpers');

/**
 * Rewrite asset URLs in HTML for WordPress
 * Converts src="assets/..." to <?php echo get_template_directory_uri(); ?>/assets/...
 */
function rewriteAssetsForWordPress(html) {
  if (!html || typeof html !== 'string') return html;

  let processed = html;

  // Rewrite image sources: src="assets/..." or src="./assets/..."
  processed = processed.replace(
    /(src=["'])(\.?\/?assets\/[^"']+)(["'])/gi,
    '$1<?php echo esc_url( get_template_directory_uri() ); ?>/assets/$3'
  );

  // Rewrite href attributes (for links to assets)
  processed = processed.replace(
    /(href=["'])(\.?\/?assets\/[^"']+)(["'])/gi,
    '$1<?php echo esc_url( get_template_directory_uri() ); ?>/assets/$3'
  );

  // Rewrite background images in style attributes
  processed = processed.replace(
    /(background(?:-image)?\s*:\s*url\(\s*["']?)(\.?\/?assets\/[^"')]+)(["']?\s*\))/gi,
    '$1<?php echo esc_url( get_template_directory_uri() ); ?>/assets/$3'
  );

  // Rewrite srcset attributes for responsive images
  processed = processed.replace(
    /(srcset=["'][^"']*)(\.?\/?assets\/[^"',\s]+)/gi,
    (match, prefix, assetPath) => {
      return prefix + '<?php echo esc_url( get_template_directory_uri() ); ?>/assets/' + assetPath.replace(/^\.?\/?assets\//, '');
    }
  );

  return processed;
}

/**
 * Generate the theme-page-content.php data file
 * Contains all extracted content for each page (stored as flat key-value pairs)
 *
 * @param {object} pageContents - Object where keys are page slugs, values are content objects
 * @param {object} pageContents[slug] - Flat object of field keys to values
 * @example
 * {
 *   'about': {
 *     'hero_h1': 'About Acme Plumbing',
 *     'hero_tagline': 'Serving Austin since 1995',
 *     'section_0_h2_0': 'Our Story',
 *     'section_0_p_0': 'We started...',
 *     'section_0_p_1': 'Today we...'
 *   },
 *   'water-heater-repair': { ... }
 * }
 * @returns {string} - Complete PHP array as string
 */
function generateThemeContentPhp(pageContents) {
  if (!pageContents || typeof pageContents !== 'object' || Object.keys(pageContents).length === 0) {
    return `<?php
/**
 * Theme Page Content
 * This file is empty because no page content was extracted.
 */
return [];
`;
  }

  // Build each page's content entry
  const entries = Object.entries(pageContents).map(([slug, content]) => {
    const escapedSlug = phpEscapeSingle(slug);
    
    // Convert content object to PHP array with proper escaping
    const contentArray = buildContentArray(content);

    return `    '${escapedSlug}' => ${contentArray}`;
  }).join(",\n\n");

  return `<?php
/**
 * Theme Page Content
 * 
 * This file contains all extracted text content from the static HTML pages.
 * Content is organized by page slug and stored as key-value pairs.
 * 
 * On theme activation, this content is imported into WordPress post meta,
 * allowing users to edit it through the admin interface.
 * 
 * Structure:
 * [
 *   'page-slug' => [
 *     'hero_h1' => 'Main Heading',
 *     'hero_tagline' => 'Tagline text',
 *     'section_0_h2_0' => 'Section heading',
 *     'section_0_p_0' => 'First paragraph',
 *     ...
 *   ]
 * ]
 * 
 * This file is automatically generated from your static HTML build.
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return [
${entries}
];
`;
}

/**
 * Build PHP array syntax for content object
 * NOW: Rewrites asset URLs before storing and handles HTML content
 *
 * @param {object} content - Flat content object
 * @returns {string} - PHP array syntax
 */
function buildContentArray(content) {
  if (!content || typeof content !== 'object') {
    return '[]';
  }

  const entries = Object.entries(content)
    .filter(([_, value]) => value !== null && value !== undefined && value !== '')
    .map(([key, value]) => {
      const escapedKey = phpEscapeSingle(key);
      
      // Convert value to string
      let processedValue = String(value);
      
      // Check if value contains HTML (images, tags, etc.)
      const hasHtml = processedValue.includes('<') || 
                      processedValue.includes('img') || 
                      processedValue.includes('src=');
      
      // If it has HTML with asset references, rewrite the paths
      if (hasHtml && (processedValue.includes('assets/') || processedValue.includes('./assets/'))) {
        processedValue = rewriteAssetsForWordPress(processedValue);
      }
      
      // Escape for PHP string
      const escapedValue = phpEscapeSingle(processedValue);
      
      return `        '${escapedKey}' => '${escapedValue}'`;
    });

  if (entries.length === 0) {
    return '[]';
  }

  return `[\n${entries.join(",\n")}\n    ]`;
}

/**
 * Merge multiple page content objects
 * Useful when combining content from different sources
 *
 * @param {array} contentObjects - Array of page content objects to merge
 * @returns {object} - Merged content object
 */
function mergePageContents(...contentObjects) {
  const merged = {};

  contentObjects.forEach(obj => {
    if (obj && typeof obj === 'object') {
      Object.entries(obj).forEach(([slug, content]) => {
        if (!merged[slug]) {
          merged[slug] = {};
        }
        // Merge content, later objects override earlier ones
        Object.assign(merged[slug], content);
      });
    }
  });

  return merged;
}

/**
 * Filter out empty content fields
 * Removes fields with empty strings, null, or undefined values
 *
 * @param {object} pageContents - Page content object
 * @returns {object} - Cleaned page content object
 */
function filterEmptyFields(pageContents) {
  const cleaned = {};

  Object.entries(pageContents).forEach(([slug, content]) => {
    const cleanedContent = {};

    Object.entries(content).forEach(([key, value]) => {
      // Keep field if it has meaningful content
      if (value !== null && value !== undefined && String(value).trim() !== '') {
        cleanedContent[key] = value;
      }
    });

    // Only include page if it has at least one field
    if (Object.keys(cleanedContent).length > 0) {
      cleaned[slug] = cleanedContent;
    }
  });

  return cleaned;
}

/**
 * Get content summary for logging/debugging
 * Shows how many fields each page has
 *
 * @param {object} pageContents - Page content object
 * @returns {object} - Summary object { slug: fieldCount }
 */
function getContentSummary(pageContents) {
  const summary = {};

  Object.entries(pageContents).forEach(([slug, content]) => {
    summary[slug] = Object.keys(content).length;
  });

  return summary;
}

/**
 * Validate page content structure
 * Checks if content has required fields
 *
 * @param {object} content - Single page's content object
 * @returns {object} - { valid: boolean, missing: array }
 */
function validatePageContent(content) {
  const requiredFields = ['hero_h1']; // At minimum, pages should have a main heading
  const missing = [];

  requiredFields.forEach(field => {
    if (!content[field] || String(content[field]).trim() === '') {
      missing.push(field);
    }
  });

  return {
    valid: missing.length === 0,
    missing,
  };
}

/**
 * Convert structured content to flat content
 * Takes extracted content with nested structure and flattens it
 * (This is a convenience wrapper for the flattenContentForMeta function)
 *
 * @param {object} extractedContent - Structured content from contentExtractor
 * @returns {object} - Flat content object ready for theme-page-content.php
 */
function structuredToFlatContent(extractedContent) {
  const { flattenContentForMeta } = require('../extractors/contentExtractor');
  return flattenContentForMeta(extractedContent);
}

module.exports = {
  generateThemeContentPhp,
  buildContentArray,
  mergePageContents,
  filterEmptyFields,
  getContentSummary,
  validatePageContent,
  structuredToFlatContent,
  rewriteAssetsForWordPress  // Export for use in other modules
};